### ISSUE TITLE
Git Error | warning: Clone succeeded, but checkout failed.

### ISSUE THREAD

**Issue by finalelement** [MASILab/PreQual#1]
If the repository is directly cloned, an error (Posted at the end of the description of the issue) pops up. I am not sure if it can be ignored, but at my end the issue does not allow proceeding with the 'git checkout' of the appropriate version

`/scratch/prequal_singularity$ git clone https://github.com/MASILab/PreQual.git
Cloning into 'PreQual'...
remote: Enumerating objects: 365, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 365 (delta 23), reused 49 (delta 17), pack-reused 304
Receiving objects: 100% (365/365), 391.26 MiB | 52.41 MiB/s, done.
Resolving deltas: 100% (167/167), done.
error: inflate: data stream error (incorrect data check)
fatal: packed object e7d52b919afebedb532ddbfea964f9e1cf0e163b (stored in /scratch/prequal_singularity/PreQual/.git/objects/pack/pack-02dd29000cb5db4b51072fa33e76b2d6702af9d3.pack) is corrupt
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`

**Comment by leonyichencai** [comment]
Hmm I was able to clone directly (below). Can you try cloning into another directory or with another machine? It looks like a common reason for this git issue is people running out of disk space? Alternatively, what does `git status` reveal?

`caily@masi-18:/home-local/caily/PreQual$ git clone https://github.com/MASILab/PreQual.git
Cloning into 'PreQual'...
remote: Enumerating objects: 365, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 365 (delta 23), reused 49 (delta 17), pack-reused 304
Receiving objects: 100% (365/365), 391.26 MiB | 62.90 MiB/s, done.
Resolving deltas: 100% (167/167), done.
Checking out files: 100% (34/34), done.
caily@masi-18:/home-local/caily/PreQual$`

**Comment by finalelement** [comment]
It worked out at my end, Thanks!
