### ISSUE TITLE
exclude topup

### ISSUE THREAD

**Issue by silvia-oxc** [MASILab/PreQual#13]
Is it possible to run only the first part of the pipeline? excluding TOPUP and all the following steps
I cannot find such a flag, while in Synb0-DISCO there was --notopup

**Comment by mkim-MASI** [comment]
As long as there is no t1 in the input directory and no opposite direction PE scans, you can run without topup.

However, there is currently no support for skipping EDDY, as many of the metrics that EDDY provides are essential to the QA process.
