### ISSUE TITLE
Request for Latest Version Download Link

### ISSUE THREAD

**Issue by Luoyu-Wang** [MASILab/PreQual#14]
Hello,

I'm currently using version 1.0.8 in the README. Could you please provide a download link for the most recent version? I couldn't find it on the repository.

Thank you for your assistance!

**Comment by mkim-MASI** [comment]
Please find the links here:

https://github.com/MASILab/PreQual/releases/tag/v1.1.0

**Comment by Luoyu-Wang** [comment]
In fact, we have been attempting to build it, but have not been successful so far. Could you provide a SIF file to assist us?

**Comment by mkim-MASI** [comment]
When building, perhaps try replacing the fslinstaller that is currently in there with the following line:

https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/releases/fslinstaller.py

If it is not the FSLinstaller, please comment on what the exact issue is with the error messages

**Comment by Luoyu-Wang** [comment]
Hi! Thank you  for your guidance, the problem we are having at the moment is that the dipy version seems to be incompatible:

Collecting dipy==1.5.* (from scilpy==1.4)
  Downloading dipy-1.5.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (3.9 kB)
WARNING: Ignoring version 1.5.0 of dipy since it has invalid metadata:
Requested dipy==1.5.* from https://files.pythonhosted.org/packages/c5/c7/5be9c988e7ee25515b9abe02f891405d0848b28cbff1ab2e19ea21bccd84/dipy-1.5.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (from scilpy==1.4) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    fury (>=0.8.0scikit-learn) ; extra == 'all'
         ~~~~~~~~^
Please use pip<24.1 if you need to use this version.
INFO: pip is looking at multiple versions of scilpy to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.9.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement dipy==1.5.* (from scilpy) (from versions: 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.9.1, 0.9.2, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0)
ERROR: No matching distribution found for dipy==1.5.*
Could you tell us how we can fix this or provide a sif file for the most recent version ?

**Comment by KarthikMasi** [comment]
here is a fully built container: https://vanderbilt.box.com/s/vajral9xf99q4flshm4bfenbz3ax6jn8

**Comment by Luoyu-Wang** [comment]
> here is a fully built container: https://vanderbilt.box.com/s/vajral9xf99q4flshm4bfenbz3ax6jn8

Thank you for sharing the link. However, the provided version 1.0.6 does not include the gradient non-linearity correction feature, which is essential for our HCP data processing. Could you please supply the link for version 1.1.0 that includes this functionality? We greatly appreciate your assistance.
