### ISSUE TITLE
Problem running PreQual on singularity 3.8

### ISSUE THREAD

**Issue by jw-research** [MASILab/PreQual#2]
Hello!

I've recently started using PreQual for a current project but encountered a problem: 

The pipeline runs perfectly on a server running singularity 2.4.2. As I want to use GPU for running advanced EDDY options, I would want to run it on a server with GPU and also CUDA installed. These servers run singularity 3.8.0, and every time I've tried using the pipeline (no matter the exact command) here, I've gotten a "**INFO: Converting SIF file to temporary sandbox...**" message, which then ends after a few minutes in a fatal error due to "**no space left on device**". (see below for entire message)

`INFO: Converting SIF  file to temporary sandbox...`
`FATAL: while extracting /sw/singularityImages/s2/prequal.simg: root filesystem extraction failed: failed to copy content in staging file: write /tmp/rootfs-047181571/archive-275866246: no space left on device`

We found this curious as it only seems to occur when using this version of singularity, we've also tried different locations (with definitely enough space) for /tmp but it hasn't changed anything. The image is saved in .simg format, so it is also unclear to me while it even needs to be converted (which doesn't happen with singularity 2.4.2) - do you have any idea what could help?

Thank you for any help and kind greetings,
Jil W.

**Comment by mkim-MASI** [comment]
Hi Jil,

We can run using `singularity-ce version 3.8.0` on local hardware and `singularity version 3.8.7-1.el7` on our larger servers. 

As a temporary solution, you might be able to specify a different temp directory location with more storage space.
