### ISSUE TITLE
Add Patch2Self denoising in PreQual?

### ISSUE THREAD

**Issue by ShreyasFadnavis** [MASILab/PreQual#3]
Hi,

I wanted to ask if it is of interest to add Patch2Self in PreQual? It is pretty simple to add to the code-base:
Command line:
`dipy_denoise_patch2self data.nii.gz bvals --verbose`

Python:
```
from dipy.denoise.patch2self import patch2self

denoised_array = patch2self(data, bvals, verbose=True)
```

Let me know if you need help with this!

Thanks,
Shreyas

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
